export type Product={name:string;category:string;type:string;summary:string;applications:string[];benefits:string[]};

// Technical entries for ingredients whose class and mode of action are established,
// public feed-science (not proprietary claims about a specific formulation).
// Anything not listed here falls back to the category-level technical framing below —
// exact specifications, dose rates and trial data live in the real spec sheet, not this site.
const TECH:Record<string,{summary:string;applications:string[];benefits:string[]}>={
 'Amylase':{summary:'An α-amylase that hydrolyses the α-1,4 glycosidic bonds in starch, breaking it down into shorter dextrins and fermentable sugars.',applications:['Cereal-based broiler and layer diets','Young-animal diets where endogenous amylase secretion is still developing'],benefits:['Improves starch digestibility and energy availability from the diet','Reduces variability in raw-material starch quality across batches']},
 'Beta Galactosidase':{summary:'A β-galactosidase (lactase) that hydrolyses lactose into glucose and galactose.',applications:['Milk-replacer formulations for calves and piglets','Dairy-adjacent feed applications with residual lactose'],benefits:['Supports lactose digestion in animals with limited native lactase activity','Reduces the risk of undigested-lactose-driven scouring in young stock']},
 'Beta Glucanase':{summary:'Breaks down β-glucans — non-starch polysaccharides concentrated in barley and oats — that otherwise raise digesta viscosity.',applications:['Barley- or oat-inclusion poultry and swine diets','High-viscosity NSP diets prone to sticky droppings'],benefits:['Lowers intestinal digesta viscosity for better nutrient contact and absorption','Reduces litter/manure moisture issues linked to viscous digesta']},
 'Mannanase':{summary:'A β-mannanase that hydrolyses mannan-based polysaccharides found in soybean meal and palm kernel meal.',applications:['Soybean meal or palm kernel meal-based diets','Programs targeting feed-conversion efficiency'],benefits:['Reduces the anti-nutritional load of dietary mannans','Can spare the metabolic cost of the immune response mannans otherwise trigger']},
 'Bromelain':{summary:'A cysteine protease derived from pineapple stem that hydrolyses proteins into peptides and free amino acids.',applications:['Protein digestibility programs','Feed formulations using lower-cost, harder-to-digest protein sources'],benefits:['Improves breakdown of dietary protein ahead of absorption','Supports amino acid availability from varied protein sources']},
 'Catalase':{summary:'An antioxidant enzyme that decomposes hydrogen peroxide into water and oxygen.',applications:['Feed and process streams where peroxide residues need to be managed','Oxidative-stress-sensitive formulations'],benefits:['Helps manage peroxide load in processed feed ingredients','Complements broader oxidative-stability strategies']},
 'Cellulase':{summary:'Breaks down cellulose — the β-1,4-glucan backbone of plant cell walls — releasing nutrients otherwise trapped inside fibrous material.',applications:['High-fibre or by-product-inclusion diets','Ruminant and monogastric diets with significant plant fibre content'],benefits:['Unlocks nutrients bound within plant cell-wall structures','Improves the feeding value of fibrous raw materials']},
 'Lipase':{summary:'Hydrolyses dietary triglycerides into free fatty acids and glycerol.',applications:['High-fat diets and young-animal starter feeds','Diets for species/stages with limited pancreatic lipase output'],benefits:['Improves fat digestibility, particularly in young animals','Supports energy utilisation from added dietary fats and oils']},
 'Phytase':{summary:'Hydrolyses phytate — the storage form of phosphorus in plant seeds — releasing bound phosphorus for absorption.',applications:['Grain- and oilseed-meal-based diets across poultry, swine and aquaculture','Formulations aiming to reduce inorganic phosphate inclusion'],benefits:['Reduces dependence on inorganic phosphate supplementation','Lowers phosphorus excretion, supporting environmental compliance goals','Can improve availability of phytate-bound minerals and amino acids']},
 'Protease':{summary:'Hydrolyses peptide bonds in dietary protein, breaking it down into peptides and free amino acids.',applications:['Formulations targeting reduced crude protein without a performance trade-off','Diets using variable-quality protein sources'],benefits:['Improves protein and amino acid digestibility','Supports lower dietary nitrogen excretion at matched performance']},
 'Xylanase':{summary:'A non-starch polysaccharide (NSP) enzyme that hydrolyses arabinoxylans, the viscosity-raising fibre fraction in wheat, rye and barley.',applications:['Wheat- or rye-based poultry and swine diets','Diets formulated alongside other NSP enzymes'],benefits:['Reduces digesta viscosity for improved nutrient access','Commonly paired with β-glucanase in cereal-heavy formulations']},
 'Serratiopeptidase':{summary:'A proteolytic enzyme referenced in animal-health contexts for its mucolytic and anti-inflammatory associations alongside general proteolytic activity.',applications:['Supportive formulations targeting mucosal and respiratory comfort'],benefits:['Contributes proteolytic activity alongside its mucolytic association','Used as a supporting component in targeted health formulations']},
 'Lysozyme A':{summary:'Lysozyme is a naturally occurring antimicrobial enzyme that hydrolyses the peptidoglycan cell wall of susceptible Gram-positive bacteria.',applications:['Gut-health programs targeting Gram-positive bacterial load','Young-animal formulations supporting a balanced gut microbiota'],benefits:['Direct antibacterial action against susceptible Gram-positive species','A naturally derived alternative component within gut-health strategies']},
 'Bacillus':{summary:'Spore-forming probiotic bacteria. The spore form survives feed pelleting heat and gastric transit, then germinates in the intestine.',applications:['Heat-processed (pelleted/extruded) feed where probiotic survival through processing matters','Gut-health and competitive-exclusion programs'],benefits:['Withstands feed manufacturing heat better than non-spore-forming probiotics','Germinates in situ to compete with pathogenic bacteria for gut attachment sites']},
 'Lactobacillus':{summary:'Lactic-acid-producing bacteria that lower local gut pH as they ferment available substrates.',applications:['Gut microbiota balance programs across species','Young-animal starter programs'],benefits:['Lactic acid production creates conditions less favourable to acid-sensitive pathogens','Supports a more stable gut microbial balance']},
 'Bifidobacterium':{summary:'Bacteria associated with intestinal barrier support and modulation of the gut microbiota, most established in young monogastric animals.',applications:['Piglet and poultry starter gut-health programs'],benefits:['Associated with intestinal barrier integrity support','Contributes to a favourable early-life gut microbial profile']},
 'Enterococcus':{summary:'Lactic-acid bacteria; select non-pathogenic strains are used as probiotics in poultry and swine gut-health programs.',applications:['Gut-health and microbial-balance formulations'],benefits:['Lactic-acid metabolism supportive of gut pH balance','Used as one component within multi-strain probiotic strategies']},
 'Prebiotics':{summary:'Non-digestible feed ingredients (such as mannan- or fructo-oligosaccharides) that selectively support beneficial gut microbial populations, and in the case of mannan-based prebiotics can bind certain pathogenic bacteria directly.',applications:['Combined with probiotic strains as part of a gut-health program','Diets targeting reduced pathogen colonisation pressure'],benefits:['Selectively feeds beneficial gut microbial populations','Mannan-based prebiotics can bind type-1 fimbriated pathogens, limiting gut wall attachment']},
 'Neovitaz AD3.E':{summary:'A fat-soluble vitamin premix built around Vitamin A, D3 and E — vitamins that depend on dietary fat for absorption and are commonly supplemented together.',applications:['Baseline vitamin fortification across poultry, dairy and livestock diets'],benefits:['Vitamin A supports epithelial and immune function','Vitamin D3 supports calcium and phosphorus metabolism','Vitamin E functions as a biological antioxidant']},
};

// Category-level technical framing used when a specific product name isn't in TECH above —
// still grounded in the real function of that product class, just without claiming
// proprietary specifics this site can't verify.
const CATEGORY_FALLBACK:Record<string,{summaryTail:string;applications:string[];benefits:string[]}>={
 'Poultry Nutrition':{summaryTail:'formulated for gut health, digestion and feed-conversion efficiency in broiler and layer programs.',applications:['Broiler and layer feed programs','Gut-health and feed-conversion support'],benefits:['Designed for integration into standard poultry feed formulations','Supports feed conversion ratio (FCR) and gut-health objectives']},
 'Dairy & Cattle':{summaryTail:'formulated to support digestion, mineral status or metabolic function in dairy and cattle nutrition programs.',applications:['Dairy and cattle ration formulation','Transition-period and lactation support programs'],benefits:['Designed for integration into standard dairy and cattle feed programs','Supports digestive, metabolic or mineral-status objectives depending on formulation']},
 'Aquaculture':{summaryTail:'formulated to support pond water quality, gut health or growth performance in aquaculture programs.',applications:['Pond-based aquaculture programs','Water-quality and gut-health management'],benefits:['Designed for integration into standard aquaculture feed or pond-management programs','Supports water-quality or animal-health objectives depending on formulation']},
 'Feed Additives':{summaryTail:'a functional feed ingredient used to support mineral status, gut function or overall feed performance.',applications:['Feed-industry formulation as a functional additive','Programs targeting a specific nutritional or performance objective'],benefits:['Formulated as a functional component of broader feed programs','Technical specification available on request']},
};

const make=(names:string[],category:string,type:string,application:string)=>names.map(name=>{
 const tech=TECH[name];
 if(tech)return{name,category,type,summary:tech.summary,applications:tech.applications,benefits:tech.benefits};
 const fb=CATEGORY_FALLBACK[category];
 return{name,category,type,summary:`${name} is ${fb?fb.summaryTail:`part of the ${category.toLowerCase()} portfolio.`}`,applications:fb?fb.applications:[application],benefits:fb?fb.benefits:['Available for international B2B enquiry','Technical information available on request']};
});

export const products:Product[]=[
...make(['EnzyBond','Nutri9','M-MOS','BiomaS','AGX','Phytaaz','POWER PRO ACE','Lysozyme A','MUCINZYME','LitteraZ'],'Poultry Nutrition','Poultry solution','Poultry nutrition and feed programs'),
...make(['Neoliv','NEOBOLITE','Myeast','Neobiotic-Rz36Cr','Neobiotic-Rz36Cr Star','Spherucal','NEOMILK','NEOBIOTIC','ZYMIX','Neomin 9','M-MOS','Neomin 18','Rockett','Neovitaz AD3.E','Utrocent plus Vet.','Buffering Start','BooosT'],'Dairy & Cattle','Livestock nutrition','Dairy and cattle nutrition programs'),
...make(['Aquabiotic','M-MOS','Aquabiotic WS','Myeast AQUA','AQUABIOTIC NRB','NITROCLEAN','RHODOKLIN','AQUA PROTEXX','Neoliv Aqua'],'Aquaculture','Aquaculture solution','Aquaculture and pond-management programs'),
...make(['Amylase','Beta Galactosidase','Beta Glucanase','Mannanase','Bromelain','Catalase','Cellulase','Lipase','Phytase','Protease','Xylanase','Serratiopeptidase'],'Enzymes','Enzyme','Feed, nutrition and technical enzyme applications'),
...make(['Bacillus','Lactobacillus','Bifidobacterium','Enterococcus'],'Probiotics & Prebiotics','Microbial solution','Animal nutrition and microbial programs'),
...make(['Prebiotics'],'Probiotics & Prebiotics','Prebiotic solution','Animal nutrition and feed programs'),
...make(['Mineral supplements','Yeast-based solutions','Functional nutrition solutions'],'Feed Additives','Functional nutrition','Animal feed and nutrition programs'),
];
export const categories=[...new Set(products.map(p=>p.category))];
export const categoryMeta:Record<string,{label:string;intro:string;number:string}>={
 'Poultry Nutrition':{label:'Poultry',intro:'Enzyme, microbial and functional solutions for gut health, digestion and feed-conversion efficiency in broiler and layer programs.',number:'01'},
 'Dairy & Cattle':{label:'Dairy & Cattle',intro:'Nutrition, mineral and functional solutions spanning transition-period support, rumen function and young-stock programs.',number:'02'},
 'Aquaculture':{label:'Aquaculture',intro:'Pond water-quality, microbial and gut-health solutions for professional aquaculture programs.',number:'03'},
 'Enzymes':{label:'Enzymes',intro:'A technical enzyme portfolio spanning carbohydrases, proteases, phytase and lipase — each targeting a specific digestibility or anti-nutritional-factor challenge.',number:'04'},
 'Probiotics & Prebiotics':{label:'Probiotics & Prebiotics',intro:'Live microbial strains and non-digestible prebiotic substrates that work together to support a balanced, pathogen-resistant gut microbiome.',number:'05'},
 'Feed Additives':{label:'Feed Additives',intro:'Mineral, yeast-based and functional nutrition product families for feed-industry buyers.',number:'06'}
};
export function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export function productSlug(p:Product){return `${slugify(p.category)}--${slugify(p.name)}`}
export function getProduct(slug:string){return products.find(p=>productSlug(p)===slug)}
