export type Product={name:string;category:string;type:string;problem:string;summary:string;applications:string[];benefits:string[];problemTags:string[]};

// The "problem map" a Gujarat Enzyme field-sales guide uses to route a buyer's stated
// problem to the right products, grouped by sector. Product names below must match the
// exact names used in the `make()` calls further down this file.
export type ProblemGroup={sector:string;items:{label:string;productNames:string[]}[]};
export const problemGuide:ProblemGroup[]=[
 {sector:'Dairy & Cattle',items:[
  {label:'Low appetite, indigestion or liver',productNames:['Neoliv']},
  {label:'Energy deficit or ketosis risk',productNames:['NEOBOLITE']},
  {label:'Poor fibre digestion or feed utilisation',productNames:['Myeast','Neobiotic-Rz36Cr','Neobiotic-Rz36Cr Star','NEOBIOTIC','ZYMIX','Rockett']},
  {label:'Low milk yield or low milk fat',productNames:['NEOMILK','Rockett','BooosT','NEOBOLITE']},
  {label:'Calcium or mineral deficiency',productNames:['Spherucal','Neomin 9','Neomin 18','Neovitaz AD3.E']},
  {label:'Mycotoxin risk',productNames:['M-MOS']},
  {label:'Reproductive or uterine issues',productNames:['Utrocent plus Vet.']},
  {label:'Rumen acidosis or heat stress',productNames:['Buffering Start']},
 ]},
 {sector:'Poultry',items:[
  {label:'Poor FCR or feed efficiency',productNames:['EnzyBond','AGX','Phytaaz','POWER PRO ACE']},
  {label:'NSP or high gut viscosity',productNames:['EnzyBond','AGX']},
  {label:'Protein digestion',productNames:['POWER PRO ACE']},
  {label:'Gut health or probiotic support',productNames:['Nutri9','BiomaS','Lysozymex','MUCINZYME']},
  {label:'Mycotoxin risk or immunity',productNames:['M-MOS']},
  {label:'Fly or litter problems',productNames:['LitteraZ']},
 ]},
 {sector:'Aquaculture',items:[
  {label:'Ammonia or nitrite',productNames:['AQUABIOTIC NRB','NITROCLEAN']},
  {label:'Poor water quality or pond ecosystem',productNames:['Aquabiotic','AQUABIOTIC NRB','RHODOKLIN']},
  {label:'Poor digestion or FCR',productNames:['Aquabiotic WS','Myeast AQUA','AQUA PROTEXX']},
  {label:'Liver or feed intake',productNames:['Neoliv Aqua']},
  {label:'Mycotoxin risk',productNames:['M-MOS']},
 ]},
];
const PROBLEM_TAGS:Record<string,string[]>=(()=>{const m:Record<string,string[]>={};problemGuide.forEach(g=>g.items.forEach(it=>it.productNames.forEach(n=>{(m[n]=m[n]||[]).push(it.label)})));return m})();

// Real product data sourced from Gujarat Enzyme brochures (poultry, dairy & cattle, aquaculture),
// supplied by the client. Composition/benefit claims below are taken directly from those brochures.
// The handful of well-known standalone ingredients (Phytase, Xylanase, Bacillus, etc. under
// Enzymes / Probiotics & Prebiotics) use established public feed-science instead, since they're
// generic raw actives rather than one of the branded formulations.
const TECH:Record<string,{problem:string;summary:string;applications:string[];benefits:string[]}>={
 // ---------- POULTRY (from POULTRY_BOOK_FOR_CHANDIGADH.pdf) ----------
 'EnzyBond':{problem:'Poultry diets contain non-starch polysaccharides, phytate-bound phosphorus and variable protein/fat sources that birds can\u2019t fully break down on their own — capping feed conversion and driving up cost.',summary:'A multi-enzyme blend (cellulase, xylanase, amylase, phytase, lipase, pectinase, protease, β-glucanase, β-mannanase) formulated to maximise digestibility across the whole diet.',applications:['Broiler and layer feed programs targeting FCR improvement','Diets where feed cost reduction is a priority'],benefits:['Increases digestibility of feedstuff and improves FCR','Increases egg production','Improves bioavailability of carbohydrates, fats, proteins and phosphorus','Optimises NSP and fat digestibility, increasing the ME value of feed','Reduces gut viscosity, ammonia levels and loose droppings']},
 'Nutri9':{problem:'An unstable or underdeveloped gut microbiome in poultry directly shows up as poorer FCR, inconsistent egg quality, and a weaker immune response.',summary:'A synbiotic combining nucleotides, two Lactobacillus strains, two Saccharomyces strains and two Bacillus strains — prebiotic and probiotic components formulated to work together.',applications:['Poultry, chicks, grower and layer feed programs','Breeder stock programs targeting fertility and hatchability'],benefits:['Maintains gut microflora and improves digestion','Increases body weight and improves FCR','Maintains egg production, shell quality, fertility and hatchability','Improves livability and uniformity','Stimulates and sustains immune response']},
 'BiomaS':{problem:'Single-strain probiotics don\u2019t cover the full range of gut challenges poultry face across different life stages, from chick to breeder.',summary:'A poultry gut-specific probiotic, prebiotic and postbiotic consortium — ten Bacillus, Bifidobacterium and Lactobacillus strains plus MOS and a five-enzyme profile, fortified with B-vitamins.',applications:['Drinking-water or mash-feed gut-health programs across chicks, growers, layers and breeders'],benefits:['Optimises gut health and enhances digestion','Improves nutrient absorption and growth','Improves FCR']},
 'AGX':{problem:'Wheat, rye, barley and triticale-based diets raise gut viscosity because birds lack the enzymes to break down xylan and other plant cell-wall polysaccharides — trapping nutrient value.',summary:'A thermostable xylanase (endo-1,4-β-xylanase) and β-glucanase blend that degrades xylan and other plant cell-wall components, releasing the nutrient value locked in cereal grain endosperm.',applications:['Wheat, rye, barley or triticale-inclusion poultry diets'],benefits:['Gives flexibility in feed formulation','Reduces the negative effects of NSPs in poultry nutrition','Reduces GI tract content viscosity','Improves digestibility and absorption of nutrients, weight gain and feed efficiency']},
 'Phytaaz':{problem:'Most of the phosphorus in grain and oilseed-based poultry diets is locked in phytate and unavailable to the bird — forcing costly inorganic phosphate (DCP/MCP) supplementation.',summary:'A micronised phytase enzyme powder (minimum 5,000 FTU/g) that releases phytate-bound phosphorus along with calcium, magnesium, copper, zinc and phytate-bound protein, amino acids and starch.',applications:['Layer and broiler diets aiming to reduce DCP/MCP or bone-meal inclusion'],benefits:['Reduces the supplementation of costly inorganic phosphorus, lowering feed cost','Increases the utilisation and efficiency of minerals, protein and other nutrients','Reduces the overall cost of feed and production']},
 'POWER PRO ACE':{problem:'Lower-cost, harder-to-digest protein sources leave amino acid value on the table and raise nitrogen excretion — a real feed-cost and environmental constraint.',summary:'A protease (acid and alkaline), cellulase and amylase blend with Lactobacillus sporogenes, protein hydrolysate, amino acids and minerals, built to optimise protein digestion.',applications:['Broiler and layer diets using lower-quality or variable protein sources'],benefits:['Improves protein digestibility and absorption','Allows lower-quality protein sources to be included in feed to manage cost','Improves nutrient absorption by birds','Reduces nitrogen excretion, helping protect the environment']},
 'Lysozymex':{problem:'Antibiotic growth-promoter restrictions have left a gap for natural, residue-free tools that manage bacterial gut challenges without a withdrawal period.',summary:'A microbial-origin blend of Lysozyme, Glucose oxidase, Catalase and Vitamin C, produced via GRAS, non-GMO microbial fermentation.',applications:['Gut-health programs seeking an antibiotic-free, residue-free option','Diets where pelleting stability and vitamin/organic-acid compatibility matter'],benefits:['Minimises Gram-positive and Gram-negative bacteria','Residue-free, with no withdrawal period','Improves gut health and natural innate immunity','Stable during pelleting; compatible with vitamins and organic acids']},
 'MUCINZYME':{problem:'Excess or inappropriate mucus and respiratory inflammation in dense poultry housing quietly drag down performance and can increase reliance on antibiotics.',summary:'A mucinase and proteolytic enzyme blend that hydrolyses inappropriate or excess mucus, targeting the gel layer (MUC5AC/MUC5B) and periciliary layer of the respiratory mucosa, active at the pH 4–6 range of the poultry gut.',applications:['Respiratory-health support programs, especially in high-density housing'],benefits:['Breaks down mucin and reduces viscosity','Enhances mucociliary clearance, reducing mucus accumulation and associated health issues','Supports respiratory health, performance and immune function','May reduce antibiotic usage']},
 'LitteraZ':{problem:'Poultry house litter buildup breeds houseflies and releases ammonia and H2S — a welfare, odour and biosecurity problem that\u2019s hard to manage with a general disinfectant.',summary:'A biotech, non-toxic enzyme dusting powder for poultry litter, designed to control houseflies and speed up in-situ litter composting.',applications:['Litter bed treatment in broiler and layer houses'],benefits:['Minimises fly menace (both adult and larvae)','Drives complete litter decomposition and improves litter nutritional value','Minimises litter odour from ammonia and H2S']},
 // ---------- DAIRY & CATTLE (from Cattle_1-16.pdf) ----------
 'Neoliv':{problem:'Liver stress in dairy animals — often around calving or on high-production diets — shows up as reduced appetite, poor digestion and dropping milk output.',summary:'A liver tonic built on tricholine citrate, choline chloride, sorbitol, nicotinamide, ferric ammonium citrate, inositol and Vitamin B12, with a base fortified with crude liver extract.',applications:['Anorexia, indigestion and liver-disorder cases in cattle, horses and dogs'],benefits:['Increases appetite and improves digestion','Improves milk production','Corrects liver disorder and improves overall health']},
 'NEOBOLITE':{problem:'Around calving, dairy cows face a severe energy deficit that can trigger ketosis and fatty liver — directly hitting milk yield.',summary:'An energy-booster with liver-tonic action, combining gluconeogenic precursors, choline sources, B-vitamins, Vitamin C, folic acid and tri sodium citrate.',applications:['Early post-calving support for cows and buffaloes returning to feed'],benefits:['Helps bring the animal back to feed and optimum milk production','Helps prevent ketosis and protects against fatty liver','Improves availability of energy and FCR','Maintains udder/teat health and milk pH']},
 'Myeast':{problem:'Inconsistent dry matter intake and rumen fermentation efficiency limit how much energy and microbial protein an animal can actually extract from its feed.',summary:'A yeast product that ferments a wide range of carbohydrates and sugars, producing ethanol and CO2 as metabolites, and supplying B-vitamins and trace minerals.',applications:['Rumen fermentation support across cattle diets'],benefits:['Stimulates digestive microflora, positively affecting dry matter intake, rumen pH and nutrient digestibility','Enhances cellulolytic (fibre-digesting) bacteria, increasing the rate and efficiency of ruminal fermentation','Increases feed intake and microbial protein, extracting more energy from feedstuffs']},
 'Neobiotic-Rz36Cr':{problem:'Poor feed conversion and inconsistent milk components (SNF/fat) often trace back to viscous, poorly digested feed and gut microbial imbalance in cattle.',summary:'An organic-base powder combining organic chromium, Saccharomyces cerevisiae, Lactobacillus sporogenes, fermented live yeast culture, MOS+β-glucan and a cellulase/amylase/xylanase enzyme blend.',applications:['Cattle feed formulation targeting milk yield and composition'],benefits:['Improves dry matter intake and decreases feed viscosity','Enhances digestion of feed and fibre','Improves milk production, SNF and FAT percentage','Better utilisation of non-starch polysaccharides']},
 'Neobiotic-Rz36Cr Star':{problem:'Poor feed conversion and inconsistent milk components (SNF/fat) often trace back to viscous, poorly digested feed and gut microbial imbalance in cattle.',summary:'The starch-base variant of Neobiotic-Rz36Cr — the same organic chromium, yeast culture, Lactobacillus sporogenes, MOS+β-glucan and enzyme blend, on a starch carrier.',applications:['Cattle feed formulation targeting milk yield and composition'],benefits:['Improves dry matter intake and decreases feed viscosity','Enhances digestion of feed and fibre','Improves milk production, SNF and FAT percentage','Better utilisation of non-starch polysaccharides']},
 'Spherucal':{problem:'Calcium deficiency around calving is a leading cause of milk fever and uterine prolapse in dairy cattle.',summary:'An organic calcium source built on Microcrystalline Hydroxyapatite Complex (MCHC), providing calcium, phosphorus, Vitamin D3, Vitamin B12, magnesium and manganese.',applications:['Pregnant and milch animal calcium support'],benefits:['Improves milk quality and quantity','Improves blood calcium level of pregnant and milch animals','Minimises calcium-deficiency disorders like milk fever, uterine prolapse and ruminal stress']},
 'NEOMILK':{problem:'Repeat-breeder cows and animals recovering from antibiotic therapy often show poor conception rates and irregular heat cycles alongside lower milk output.',summary:'A milk-booster formula blending herbs and synthetic ingredients, fortified with an energy source and minerals.',applications:['Repeat-breeder and post-antibiotic-therapy reproductive support'],benefits:['Improves milk yield and FAT percentage','Minimises residual effects of antibiotic therapy','Helps improve conception ratio for repeat breeders and induces/regulates heat periods','Improves reproductive performance and nutritional status']},
 'NEOBIOTIC':{problem:'Poor NSP digestibility and gut viscosity quietly raise feed cost per unit of milk produced.',summary:'A synbiotic with minerals — MOS+β-glucan, fermented live yeast culture, Saccharomyces cerevisiae, two Bacillus strains, plus calcium, phosphorus, zinc, manganese and copper.',applications:['General cattle, sheep and goat feed formulation'],benefits:['Improves bioavailability of carbohydrate and protein','Optimises digestibility of non-starch polysaccharides','Delivers feed cost savings and reduces gut viscosity']},
 'ZYMIX':{problem:'Non-starch polysaccharides in cattle feed limit nutrient uptake and cap milk fat percentage and yield.',summary:'A fibrolytic multi-enzyme blend (cellulase, xylanase, amylase, pectinase, phytase) powered by essential trace minerals (cobalt, copper, zinc and ferrous sulphate).',applications:['Cattle feed formulation targeting milk yield and FCR'],benefits:['Better utilisation of non-starch polysaccharides','Better milk fat percentage and milk yield','Decreases feed viscosity and maximises nutrient uptake','Better feed conversion ratio']},
 'Neomin 9':{problem:'A gap in vitamin and trace-mineral status in cattle diets shows up as poor calf growth, stress sensitivity and lower fertility or milk output.',summary:'A vitamin and mineral premix (Vitamins A, D3, B2, B12, E, calcium D-pantothenate, biotin, plus calcium, phosphorus and a full trace-mineral profile), fortified with Jivanti and Shatavari herbs and antioxidants.',applications:['Baseline vitamin/mineral fortification for calves, heifers and lactating cattle'],benefits:['Optimises growth and health of calves and heifers','Alleviates stress and related disorders','Enhances immunity and fertility','Boosts milk production of lactating animals']},
 'Neomin 18':{problem:'A gap in vitamin and trace-mineral status in cattle diets shows up as poor calf growth, stress sensitivity and lower fertility or milk output.',summary:'An expanded vitamin and mineral premix (Vitamins A, D3, E, B12, B2, calcium D-pantothenate, biotin, plus an 11-element mineral profile including iodine and sulphur), with a Shatavari and Jivanti herbal profile.',applications:['Baseline vitamin/mineral fortification for calves, heifers and lactating cattle'],benefits:['Optimises growth and health of calves and heifers','Alleviates stress and related disorders','Enhances immunity and fertility','Boosts milk production of lactating animals']},
 'Rockett':{problem:'Picky eaters and off-feed cattle — common after stress, illness or a feed change — need a palatability and digestion boost to get back to normal intake and milk output.',summary:'A yeast, probiotic and enzyme blend (40% Saccharomyces cerevisiae, Lactobacillus sporogenes, cellulase/amylase/xylanase) with a 20% herbal profile of ginger, black pepper, long pepper, rock salt, black salt, pomegranate and ajwain.',applications:['Appetite and intake support for cattle coming off feed'],benefits:['Works as a natural, strong appetiser','Improves digestion of feed and fibre','Improves milk production and SNF/FAT percentage','Improves utilisation of non-starch polysaccharides and nutrient availability']},
 'Neovitaz AD3.E':{problem:'A gap in fat-soluble vitamin status shows up quietly — as weaker immunity, poorer bone mineralisation, reduced antioxidant defence and thinner milk.',summary:'A fat-soluble vitamin premix built on Vitamin A, D3 and E on an organic-matter base.',applications:['Baseline vitamin fortification across poultry, dairy and livestock diets'],benefits:['Supports thick, creamy milk and increased milk production','Supports better growth, productivity and reproductive performance','Boosts immunity and optimises skin coat condition and calcium absorption']},
 'Utrocent plus Vet.':{problem:'Incomplete uterine involution after calving delays the return to normal reproductive cycling and can leave discharge unresolved.',summary:'An herbal formulation of Gokharu, Shatavari, Klonji, Hirabol, Chitrak, Manjishtha and Lodhar.',applications:['Post-calving uterine health support in cattle, buffalo, sheep, goats and horses'],benefits:['Helps keep the uterus clean and promotes uterine involution','Helps the next reproduction cycle onset normally','Helps control vaginal discharge']},
 'Buffering Start':{problem:'Ruminal acidosis and heat stress panting are common, costly disruptions in intensive cattle and buffalo operations.',summary:'A rumen buffer fortified with yeast, indicated for ruminal acidosis, laminitis and panting under heat stress.',applications:['Short-course rumen-stability support during acidosis, laminitis or heat-stress episodes'],benefits:['Targets ruminal acidosis and laminitis','Supports animals panting under heat stress']},
 'BooosT':{problem:'Depressed feed intake directly caps milk yield, whatever else is right about the ration.',summary:'A live yeast culture, prebiotic/probiotic and amino acid blend.',applications:['General feed-intake and milk-yield support'],benefits:['Boosts up feed intake','Improves milk yield']},
 // ---------- AQUACULTURE (from aqua_12_page.pdf) ----------
 'Aquabiotic':{problem:'Pond bottoms accumulate organic waste and uneaten feed that degrade water quality and stress stocked animals.',summary:'A pond-management blend of four Bacillus probiotic strains and a five-enzyme profile (protease, amylase, cellulase, xylanase, β-glucanase).',applications:['Shrimp pond preparation and ongoing pond management','Fish and other aquaculture species pond maintenance'],benefits:['Degrades organic waste and litter, improving the pond environment','Thermostable, broad-spectrum, eco-friendly and biodegradable','Non-pathogenic with specific, targeted action']},
 'Aquabiotic WS':{problem:'Loose-shell syndrome and poor FCR in shrimp and prawn farming often trace back to inadequate protein and phosphorus digestion in the gut.',summary:'A feed probiotic combining four probiotic strains, Saccharomyces cerevisiae yeast, a six-enzyme profile (amylase, phytase, protease, cellulase, beta-galactosidase, lipase) and a vitamin profile.',applications:['Shrimp, prawn and fish feed supplementation'],benefits:['Improves digestive system efficiency and nutrient absorption/synthesis','Phytase improves phosphorus availability; protease improves digestion of proteinaceous material','Multi-enzyme action helps check loose-shell problems','Improves FCR, growth rate and weight gain']},
 'Myeast AQUA':{problem:'Frequent water exchange and stress-related infection susceptibility are recurring costs in intensive aquaculture.',summary:'The aquaculture application of Myeast — fermenting carbohydrates and sugars to produce metabolites and B-vitamins that support gut and pond ecosystem stability.',applications:['Shrimp, prawn and fish feed supplementation'],benefits:['Reduces water exchange needs and enhances the aquatic ecosystem','Maintains intestinal integrity and improves resistance to infection under stress','Improves growth performance and FCR']},
 'AQUABIOTIC NRB':{problem:'Ammonia and nitrite buildup from uneaten feed and waste is directly toxic to stocked fish and shrimp, and poor algal balance destabilises the whole pond.',summary:'A pond-ecosystem blend of nitrifying bacteria (Nitrosomonas sp. and Nitrobacter), photosynthetic bacteria (Rhodococcus sp. and Rhodobacter) and five Bacillus species.',applications:['Pond preparation and ongoing water-quality management for shrimp and fish'],benefits:['Improves soil and water quality and reduces toxic ammonia and nitrites','Enhances degradation of organic waste and helps balance pond ecology','Develops and stabilises a good algal bloom; prevents vibrio occurrence','Effective across pH 5.0–9.8 and salinity 0–50ppm']},
 'NITROCLEAN':{problem:'Ammonia and nitrite buildup from uneaten feed and waste is directly toxic to stocked fish and shrimp.',summary:'A pond-ecosystem blend of nitrifying bacteria — Nitrosomonas sp. and Nitrobacter — with five Bacillus species, that convert toxic nitrogen compounds into less harmful forms.',applications:['Ongoing aquaculture pond water-quality management'],benefits:['Reduces ammonia and nitrite levels in pond water','Effective across a wide range of pond conditions when applied on a regular interval']},
 'RHODOKLIN':{problem:'Unstable pond ecology and poor organic-waste turnover reduce the water quality stocked animals depend on.',summary:'A pond-ecosystem blend of photosynthetic bacteria — Rhodococcus sp. and Rhodobacter sp. — with five Bacillus species.',applications:['Ongoing aquaculture pond ecosystem management'],benefits:['Supports pond ecosystem balance alongside the nitrifying-bacteria products in the range']},
 'AQUA PROTEXX':{problem:'Shrimp and prawn growth performance depends on gut digestive efficiency that a single probiotic strain often can\u2019t deliver alone.',summary:'A multistrain probiotic (six genera including Bacillus, Lactobacillus, Enterococcus, Streptococcus, Pediococcus and Clostridium butyricum) with yeast and a five-enzyme profile, built for multiple protection.',applications:['Shrimp and prawn feed supplementation'],benefits:['Improves digestive system efficiency and nutrient absorption/synthesis','Phytase improves phosphorus availability; protease improves digestion of proteinaceous material','Improves FCR, growth rate and weight gain']},
 'Neoliv Aqua':{problem:'Hepatopancreas stress in shrimp and prawns from intensive feeding directly reduces growth and feed conversion.',summary:'A liver tonic for aquaculture species built on tricholine citrate, choline chloride, sorbitol, nicotinamide, ferric ammonium citrate, inositol and Vitamin B12 — no antibiotics, no side effects.',applications:['Indigestion and liver-disorder support in prawns, shrimp and fish'],benefits:['Improves liver function and reduces fat deposition','Improves FCR and weight gain; strengthens hepatopancreas function in prawns','Enhances neurological and hormonal function; speeds up healing; supports muscle and skeletal strength']},
 // ---------- Shared / cross-category real ingredients ----------
 'M-MOS':{problem:'Mycotoxin contamination and pathogen pressure in feed silently reduce immunity, growth and, in aquaculture, survival rates.',summary:'A prebiotic derived from the cell wall of Saccharomyces cerevisiae yeast, rich in mannan oligosaccharides and β-glucans.',applications:['Poultry, cattle and aquaculture feed programs targeting immune support'],benefits:['Improves immunity and animal performance','Binds mycotoxins (notably zearalenone)','Reduces mortality']},
 // ---------- Well-established standalone actives (Enzymes / Probiotics & Prebiotics categories) ----------
 'Amylase':{problem:'Cereal-based diets don\u2019t always release their full starch energy — especially in young animals whose own amylase output is still developing.',summary:'An α-amylase that hydrolyses the α-1,4 glycosidic bonds in starch, breaking it down into shorter dextrins and fermentable sugars.',applications:['Cereal-based broiler and layer diets','Young-animal diets where endogenous amylase secretion is still developing'],benefits:['Improves starch digestibility and energy availability from the diet','Reduces variability in raw-material starch quality across batches']},
 'Beta Galactosidase':{problem:'Young calves and piglets can\u2019t yet digest lactose efficiently, risking scours and wasted milk-replacer nutrition.',summary:'A β-galactosidase (lactase) that hydrolyses lactose into glucose and galactose.',applications:['Milk-replacer formulations for calves and piglets','Dairy-adjacent feed applications with residual lactose'],benefits:['Supports lactose digestion in animals with limited native lactase activity','Reduces the risk of undigested-lactose-driven scouring in young stock']},
 'Beta Glucanase':{problem:'Barley- and oat-based diets thicken in the gut, trapping nutrients and leading to wet, sticky droppings.',summary:'Breaks down β-glucans — non-starch polysaccharides concentrated in barley and oats — that otherwise raise digesta viscosity.',applications:['Barley- or oat-inclusion poultry and swine diets','High-viscosity NSP diets prone to sticky droppings'],benefits:['Lowers intestinal digesta viscosity for better nutrient contact and absorption','Reduces litter/manure moisture issues linked to viscous digesta']},
 'Mannanase':{problem:'Soybean meal and palm kernel meal contain mannans that trigger a costly immune response, quietly eating into feed efficiency.',summary:'A β-mannanase that hydrolyses mannan-based polysaccharides found in soybean meal and palm kernel meal.',applications:['Soybean meal or palm kernel meal-based diets','Programs targeting feed-conversion efficiency'],benefits:['Reduces the anti-nutritional load of dietary mannans','Can spare the metabolic cost of the immune response mannans otherwise trigger']},
 'Bromelain':{problem:'Lower-cost protein sources are often harder to digest, leaving amino acid value on the table.',summary:'A cysteine protease derived from pineapple stem that hydrolyses proteins into peptides and free amino acids.',applications:['Protein digestibility programs','Feed formulations using lower-cost, harder-to-digest protein sources'],benefits:['Improves breakdown of dietary protein ahead of absorption','Supports amino acid availability from varied protein sources']},
 'Catalase':{problem:'Peroxide residues in processed feed ingredients can compromise feed quality and put oxidative stress on the animal.',summary:'An antioxidant enzyme that decomposes hydrogen peroxide into water and oxygen.',applications:['Feed and process streams where peroxide residues need to be managed','Oxidative-stress-sensitive formulations'],benefits:['Helps manage peroxide load in processed feed ingredients','Complements broader oxidative-stability strategies']},
 'Cellulase':{problem:'Fibrous, by-product-heavy diets lock nutrients inside plant cell walls that the animal can\u2019t break open on its own.',summary:'Breaks down cellulose — the β-1,4-glucan backbone of plant cell walls — releasing nutrients otherwise trapped inside fibrous material.',applications:['High-fibre or by-product-inclusion diets','Ruminant and monogastric diets with significant plant fibre content'],benefits:['Unlocks nutrients bound within plant cell-wall structures','Improves the feeding value of fibrous raw materials']},
 'Lipase':{problem:'Young animals can\u2019t fully digest dietary fat, wasting one of the densest energy sources in the diet.',summary:'Hydrolyses dietary triglycerides into free fatty acids and glycerol.',applications:['High-fat diets and young-animal starter feeds','Diets for species/stages with limited pancreatic lipase output'],benefits:['Improves fat digestibility, particularly in young animals','Supports energy utilisation from added dietary fats and oils']},
 'Phytase':{problem:'Most of the phosphorus in grain and oilseed diets is chemically locked in phytate and unavailable to poultry, swine or fish — forcing costly inorganic phosphate supplementation and excess phosphorus in manure.',summary:'Hydrolyses phytate — the storage form of phosphorus in plant seeds — releasing bound phosphorus for absorption.',applications:['Grain- and oilseed-meal-based diets across poultry, swine and aquaculture','Formulations aiming to reduce inorganic phosphate inclusion'],benefits:['Reduces dependence on inorganic phosphate supplementation','Lowers phosphorus excretion, supporting environmental compliance goals','Can improve availability of phytate-bound minerals and amino acids']},
 'Protease':{problem:'Variable-quality protein sources reduce amino acid digestibility, driving up feed cost for every unit of growth.',summary:'Hydrolyses peptide bonds in dietary protein, breaking it down into peptides and free amino acids.',applications:['Formulations targeting reduced crude protein without a performance trade-off','Diets using variable-quality protein sources'],benefits:['Improves protein and amino acid digestibility','Supports lower dietary nitrogen excretion at matched performance']},
 'Xylanase':{problem:'Wheat- and rye-based diets raise gut viscosity, slowing nutrient absorption and hurting feed conversion.',summary:'A non-starch polysaccharide (NSP) enzyme that hydrolyses arabinoxylans, the viscosity-raising fibre fraction in wheat, rye and barley.',applications:['Wheat- or rye-based poultry and swine diets','Diets formulated alongside other NSP enzymes'],benefits:['Reduces digesta viscosity for improved nutrient access','Commonly paired with β-glucanase in cereal-heavy formulations']},
 'Serratiopeptidase':{problem:'Mucosal and respiratory stress in intensive production systems can quietly erode comfort and performance.',summary:'A proteolytic enzyme referenced in animal-health contexts for its mucolytic and anti-inflammatory associations alongside general proteolytic activity.',applications:['Supportive formulations targeting mucosal and respiratory comfort'],benefits:['Contributes proteolytic activity alongside its mucolytic association','Used as a supporting component in targeted health formulations']},
 'Bacillus':{problem:'Standard probiotics don\u2019t survive the heat of feed pelleting, so they never reach the gut alive to do their job.',summary:'Spore-forming probiotic bacteria. The spore form survives feed pelleting heat and gastric transit, then germinates in the intestine.',applications:['Heat-processed (pelleted/extruded) feed where probiotic survival through processing matters','Gut-health and competitive-exclusion programs'],benefits:['Withstands feed manufacturing heat better than non-spore-forming probiotics','Germinates in situ to compete with pathogenic bacteria for gut attachment sites']},
 'Lactobacillus':{problem:'An unstable gut pH gives pathogenic bacteria room to gain a foothold.',summary:'Lactic-acid-producing bacteria that lower local gut pH as they ferment available substrates.',applications:['Gut microbiota balance programs across species','Young-animal starter programs'],benefits:['Lactic acid production creates conditions less favourable to acid-sensitive pathogens','Supports a more stable gut microbial balance']},
 'Bifidobacterium':{problem:'Newly weaned or hatched animals have an underdeveloped gut microbiome, leaving them vulnerable in the first critical days.',summary:'Bacteria associated with intestinal barrier support and modulation of the gut microbiota, most established in young monogastric animals.',applications:['Piglet and poultry starter gut-health programs'],benefits:['Associated with intestinal barrier integrity support','Contributes to a favourable early-life gut microbial profile']},
 'Enterococcus':{problem:'Gut microbial imbalance is a common, hard-to-diagnose driver of poor early performance in poultry and swine.',summary:'Lactic-acid bacteria; select non-pathogenic strains are used as probiotics in poultry and swine gut-health programs.',applications:['Gut-health and microbial-balance formulations'],benefits:['Lactic-acid metabolism supportive of gut pH balance','Used as one component within multi-strain probiotic strategies']},
 'Prebiotics':{problem:'Even a strong probiotic needs the right substrate to establish itself and outcompete pathogens like E. coli and Salmonella.',summary:'Non-digestible feed ingredients (such as mannan- or fructo-oligosaccharides) that selectively support beneficial gut microbial populations, and in the case of mannan-based prebiotics can bind certain pathogenic bacteria directly.',applications:['Combined with probiotic strains as part of a gut-health program','Diets targeting reduced pathogen colonisation pressure'],benefits:['Selectively feeds beneficial gut microbial populations','Mannan-based prebiotics can bind type-1 fimbriated pathogens, limiting gut wall attachment']},
};

// Category-level technical framing used only for the three generic Feed Additives entries,
// which are placeholder category names rather than actual branded products.
const CATEGORY_FALLBACK:Record<string,{problem:string;summaryTail:string;applications:string[];benefits:string[]}>={
 'Feed Additives':{problem:'Baseline mineral and functional nutrition gaps quietly cap performance even when the rest of the diet is well formulated.',summaryTail:'a functional feed ingredient used to support mineral status, gut function or overall feed performance.',applications:['Feed-industry formulation as a functional additive','Programs targeting a specific nutritional or performance objective'],benefits:['Formulated as a functional component of broader feed programs','Technical specification available on request']},
};

const make=(names:string[],category:string,type:string,application:string)=>names.map(name=>{
 const tags=PROBLEM_TAGS[name]||[];
 const tech=TECH[name];
 if(tech)return{name,category,type,problem:tech.problem,summary:tech.summary,applications:tech.applications,benefits:tech.benefits,problemTags:tags};
 const fb=CATEGORY_FALLBACK[category];
 return{name,category,type,problem:fb?fb.problem:'Technical detail available on request.',summary:`${name} is ${fb?fb.summaryTail:`part of the ${category.toLowerCase()} portfolio.`}`,applications:fb?fb.applications:[application],benefits:fb?fb.benefits:['Available for international B2B enquiry','Technical information available on request'],problemTags:tags};
});

export const products:Product[]=[
...make(['EnzyBond','Nutri9','M-MOS','BiomaS','AGX','Phytaaz','POWER PRO ACE','Lysozymex','MUCINZYME','LitteraZ'],'Poultry Nutrition','Poultry solution','Poultry nutrition and feed programs'),
...make(['Neoliv','NEOBOLITE','Myeast','Neobiotic-Rz36Cr','Neobiotic-Rz36Cr Star','Spherucal','NEOMILK','NEOBIOTIC','ZYMIX','Neomin 9','M-MOS','Neomin 18','Rockett','Neovitaz AD3.E','Utrocent plus Vet.','Buffering Start','BooosT'],'Dairy & Cattle','Livestock nutrition','Dairy and cattle nutrition programs'),
...make(['Aquabiotic','M-MOS','Aquabiotic WS','Myeast AQUA','AQUABIOTIC NRB','NITROCLEAN','RHODOKLIN','AQUA PROTEXX','Neoliv Aqua'],'Aquaculture','Aquaculture solution','Aquaculture and pond-management programs'),
...make(['Amylase','Beta Galactosidase','Beta Glucanase','Mannanase','Bromelain','Catalase','Cellulase','Lipase','Phytase','Protease','Xylanase','Serratiopeptidase'],'Enzymes','Enzyme','Feed, nutrition and technical enzyme applications'),
...make(['Bacillus','Lactobacillus','Bifidobacterium','Enterococcus'],'Probiotics & Prebiotics','Microbial solution','Animal nutrition and microbial programs'),
...make(['Prebiotics'],'Probiotics & Prebiotics','Prebiotic solution','Animal nutrition and feed programs'),
...make(['Mineral supplements','Yeast-based solutions','Functional nutrition solutions'],'Feed Additives','Functional nutrition','Animal feed and nutrition programs'),
];
export const categories=[...new Set(products.map(p=>p.category))];
export const categoryMeta:Record<string,{label:string;intro:string;number:string}>={
 'Poultry Nutrition':{label:'Poultry',intro:'Enzyme, microbial and functional solutions for gut health, digestion and feed-conversion efficiency in broiler and layer programs.',number:'01'},
 'Dairy & Cattle':{label:'Dairy & Cattle',intro:'Nutrition, mineral and functional solutions spanning transition-period support, rumen function and young-stock programs.',number:'02'},
 'Aquaculture':{label:'Aquaculture',intro:'Pond water-quality, microbial and gut-health solutions for professional aquaculture programs.',number:'03'},
 'Enzymes':{label:'Enzymes',intro:'A technical enzyme portfolio spanning carbohydrases, proteases, phytase and lipase — each targeting a specific digestibility or anti-nutritional-factor challenge.',number:'04'},
 'Probiotics & Prebiotics':{label:'Probiotics & Prebiotics',intro:'Live microbial strains and non-digestible prebiotic substrates that work together to support a balanced, pathogen-resistant gut microbiome.',number:'05'},
 'Feed Additives':{label:'Feed Additives',intro:'Mineral, yeast-based and functional nutrition product families for feed-industry buyers.',number:'06'}
};
export function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export function productSlug(p:Product){return `${slugify(p.category)}--${slugify(p.name)}`}
export function getProduct(slug:string){return products.find(p=>productSlug(p)===slug)}
