export type Product={name:string;category:string;type:string;summary:string;applications:string[];benefits:string[]};
export const products:Product[]=[
...['EnzyBond','Nutri9','M-MOS','BiomaS','AGX','Phytaaz','POWER PRO ACE','Lysozyme A','MUCINZYME','LitteraZ'].map(name=>({name,category:'Poultry Nutrition',type:'Poultry solution',summary:'Product from the poultry nutrition portfolio.',applications:['Poultry feed'],benefits:['Application-focused nutrition support','Designed for modern feed programs']})),
...['Neoliv','NEOBOLITE','Myeast','Neobiotic-Rz36Cr','Neobiotic-Rz36Cr Star','Spherucal','NEOMILK','NEOBIOTIC','ZYMIX','Neomin 9','M-MOS','Neomin 18','Rockett','Neovitaz AD3.E','Utrocent plus Vet.','Buffering Start','BooosT'].map(name=>({name,category:'Dairy & Cattle',type:'Livestock nutrition',summary:'Product from the dairy and cattle portfolio.',applications:['Dairy & cattle'],benefits:['Livestock nutrition support','Designed for practical feeding programs']})),
...['Aquabiotic','M-MOS','Aquabiotic WS','Myeast AQUA','AQUABIOTIC NRB','NITROCLEAN','RHODOKLIN','AQUA PROTEXX','Neoliv Aqua'].map(name=>({name,category:'Aquaculture',type:'Aquaculture solution',summary:'Product from the aquaculture portfolio.',applications:['Aquaculture'],benefits:['Aquatic health or pond-management support','Designed for aquaculture programs']})),
...['Amylase','Beta Galactosidase','Beta Glucanase','Mannanase','Bromelain','Catalase','Cellulase','Lipase','Phytase','Protease','Xylanase','Serratiopeptidase'].map(name=>({name,category:'Enzymes',type:'Enzyme',summary:'Specialty enzyme listed in the technical portfolio.',applications:['Feed and nutrition applications'],benefits:['Supports targeted formulation objectives','Technical product for professional buyers']})),
...['Bacillus-based solutions','Lactobacillus-based solutions','Bifidobacterium-based solutions','Enterococcus-based solutions','Prebiotic solutions'].map(name=>({name,category:'Probiotics & Prebiotics',type:'Microbial / prebiotic',summary:'Microbial or prebiotic solution represented in the portfolio.',applications:['Animal nutrition'],benefits:['Supports nutrition-focused programs','Suitable for B2B technical evaluation']})),
...['Mineral supplements','Yeast-based solutions','Functional nutrition solutions'].map(name=>({name,category:'Feed Additives',type:'Functional nutrition',summary:'Feed additive family represented in the portfolio.',applications:['Animal feed'],benefits:['Functional nutrition support','Designed for feed-industry use']})),
];
export const categories=[...new Set(products.map(p=>p.category))];
export function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export function getProduct(slug:string){return products.find(p=>slugify(p.name)===slug)}
