const products = {
  'Poultry Nutrition':['EnzyBond','Nutri9','M-MOS','BiomaS','AGX','Phytaaz','POWER PRO ACE','Lysozyme A','MUCINZYME','LitteraZ'],
  'Dairy & Cattle':['Neoliv','NEOBOLITE','Myeast','Neobiotic-Rz36Cr','Neobiotic-Rz36Cr Star','Spherucal','NEOMILK','NEOBIOTIC','ZYMIX','Neomin 9','M-MOS','Neomin 18','Rockett','Neovitaz AD3.E','Utrocent plus Vet.','Buffering Start','BooosT'],
  'Aquaculture':['Aquabiotic','M-MOS','Aquabiotic WS','Myeast AQUA','AQUABIOTIC NRB','NITROCLEAN','RHODOKLIN','AQUA PROTEXX','Neoliv Aqua'],
  'Enzymes':['Amylase','Beta Galactosidase','Beta Glucanase','Mannanase','Bromelain','Catalase','Cellulase','Lipase','Phytase','Protease','Xylanase','Serratiopeptidase'],
  'Probiotics & Prebiotics':['Bacillus-based solutions','Lactobacillus-based solutions','Bifidobacterium-based solutions','Enterococcus-based solutions','Prebiotic solutions'],
  'Feed Additives':['Mineral supplements','Yeast-based solutions','Functional nutrition solutions']
};
export default function Products(){return <main style={{minHeight:'100vh',background:'#f5f2ea'}}><header style={{background:'#102a22',color:'#fff',padding:'24px 0'}}><div className="container" style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><a className="logo" href="/">PAUL GLOBAL</a><a className="btn btn-gold" href="/#contact">Request a Quote ↗</a></div></header><section className="section"><div className="container"><div className="eyebrow">Product catalogue</div><h1 className="serif" style={{fontSize:'clamp(52px,7vw,90px)',lineHeight:.95,margin:'15px 0 25px'}}>Explore the<br/>portfolio.</h1><p className="muted" style={{maxWidth:650}}>Browse products by category. Technical claims and specifications will be expanded only where supported by the source catalogue.</p>{Object.entries(products).map(([cat,items])=><section key={cat} id={cat.toLowerCase().replaceAll(' ','-')} style={{marginTop:80}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',borderBottom:'1px solid #ccd4cc',paddingBottom:18}}><h2 className="serif" style={{fontSize:42,margin:0}}>{cat}</h2><span className="eyebrow">{items.length} products / solutions</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12,marginTop:20}}>{items.map((p,i)=><article key={`${cat}-${p}`} style={{background:'#fff',padding:'25px',minHeight:145,border:'1px solid #e3e6df'}}><span style={{fontSize:11,color:'#7a857e'}}>PRODUCT {String(i+1).padStart(2,'0')}</span><h3 className="serif" style={{fontSize:25,margin:'14px 0 8px'}}>{p}</h3><a href="#contact" style={{fontSize:12,fontWeight:700}}>Request information ↗</a></article>)}</div></section>)}</div></section></main>}
